components/ContextMenu.tsx
components/RouterButtons.tsx

fixes #12 
The Sun enter the Capricorn

fix router controls

---

next-env.d.ts

fixes #19 
Halley's Comet comes around more than I do

fix styled jsx type error

---

.github/workflows/chromatic.yml
README.md
package-lock.json
package.json
stories/Introduction.stories.mdx

deploy storybook

---

components/ContentContainer.tsx
layouts/playlist/index.tsx
pages/404.tsx
pages/500.tsx
pages/album/[albumId].tsx
pages/artist/[artistId].tsx
pages/collection/albums.tsx
pages/collection/artists.tsx
pages/collection/playlists.tsx
pages/collection/podcasts.tsx
pages/dashboard.tsx
pages/episode/[episodeId].tsx
pages/genre/[genre].tsx
pages/search.tsx
pages/show/[show].tsx
pages/track/[id].tsx
pages/user/[userId].tsx

Truth hurts, needed something more exciting

unified main container

---

components/BigPill.tsx
components/Carousel.tsx
components/ContentContainer.tsx
components/DeviceConnectControl.tsx
components/EpisodeCard.tsx
components/Eyebrow.tsx
components/FirstTrackContainer.tsx
components/Heading.tsx
components/PageHeader.tsx
components/RemoveTracksModal.tsx
layouts/playlist/index.tsx
pages/404.tsx
pages/500.tsx
pages/artist/[artistId].tsx
pages/collection/albums.tsx
pages/collection/artists.tsx
pages/collection/playlists.tsx
pages/collection/podcasts.tsx
pages/dashboard.tsx
pages/episode/[episodeId].tsx
pages/genre/[genre].tsx
pages/search.tsx
pages/show/[show].tsx
pages/track/[id].tsx
types/heading.ts
utils/getHeadingStyles.ts

The itsy bitsy spider went up the water spout
Downed all the beer to drown the voices out

add headings system

---

components/RouterButtons.tsx

fix router buttons staying active

---

components/CardContent.tsx
components/FirstTrackContainer.tsx
components/PageDetails.tsx
components/PageHeader.tsx
components/PresentationCard.tsx
components/SingleTrackCard.tsx
utils/getMainColorFromImage.ts

fix unsecure operation

---

components/CardContent.tsx
components/PresentationCard.tsx

fix card width

---

pages/search.tsx

when searching a result we can only see 5 playlists and carousel button enable

remove search playlist limit

---

components/FirstTrackContainer.tsx
components/Heading.tsx
types/heading.ts
utils/getHeadingStyles.ts

fix firstTrackContainer multiline

---

components/CardContent.tsx
components/PresentationCard.tsx
context/UserContext.tsx
layouts/playlist/index.tsx
pages/album/[albumId].tsx
pages/artist/[artistId].tsx
pages/dashboard.tsx
pages/show/[show].tsx
pages/user/[userId].tsx

fixed #43 You're just too good to be true

fix recently played card

---

components/NowPlaying.tsx
components/PageHeader.tsx
context/SpotifyContext.tsx
pages/api/spotify-refresh.ts
pages/dashboard.tsx
pages/index.tsx
utils/cookies.ts

add same site to cookies

---

components/FullScreenLyrics.tsx

add dir auto to full screen lyrics

---

README.md

add info getting the env config

add running locally info

---

.eslintrc.js
components/CardTrack.tsx
components/DeviceConnectControl.tsx
components/PlayButton.tsx
components/PlaylistText.tsx
components/VolumeControl.tsx
components/__tests__/CardTrack.spec.tsx
context/SpotifyContext.tsx
hooks/useSpotifyPlayer.ts
stories/EpisodeCard.stories.tsx
utils/__tests__/callPictureInPicture.spec.ts
utils/callPictureInPicture.ts
utils/spotifyCalls/transferPlayback.ts

Should fix #49 
Espero con el tiempo justiciero

fix: tracks not playing

---

components/EpisodeCard.tsx
components/NowPlaying.tsx
components/PageDetails.tsx
components/PageHeader.tsx
components/PlaylistText.tsx
components/SideBar.tsx
context/SpotifyContext.tsx
layouts/playlist/index.tsx
pages/artist/[artistId].tsx
pages/concert/[id].tsx
types/pageHeader.ts
types/spotify.ts
utils/getSetList.ts

small fixes

---

components/NowPlaying.tsx
components/PictureInPictureButton.tsx
context/SpotifyContext.tsx

onclick pip button is updating the nowplaying component

fix: pip update

---

context/SpotifyContext.tsx

pip not updating when changing song

revert call pip

---

components/PageHeader.tsx
utils/getTranslations.ts

little translations fixes

---

components/Footer.tsx
components/RemoveTracksModal.tsx
package-lock.json
package.json
pages/api/lyrics.ts
utils/getLyrics.ts
utils/getTranslations.ts

Oh you big mad? Oh you big mad

Lyrics again

---

pages/api/lyrics.ts

Losin' control now

---

utils/getArtistInfo.ts

fix catch audiodb error

---

components/FullScreenLyrics.tsx
components/PictureInPictureButton.tsx
context/SpotifyContext.tsx
types/spotify.ts
utils/callPictureInPicture.ts

I'm overheated, can't be defeated Can't be deleted, can't be repeated

add picture in picture lyrics

---

components/FullScreenLyrics.tsx
utils/getLinesFittingCanvas.ts

fix: Lines that were too long were coming off the canvas

---

components/ContentContainer.tsx
layouts/MainLayout.tsx

fix scrollbar pointer

---

components/CardTrack.tsx
components/TrackListHeader.tsx

fix add button width

---

components/TopBar.tsx
pages/dashboard.tsx

I though about this but never use it

fix disable background

---

components/PlayerControls.tsx
components/icons/Repeat.tsx
context/SpotifyContext.tsx
hooks/useSpotifyPlayer.ts
types/spotify.ts

repeat is still broken, sdk not updating player state changed when repeat api is called

sync controls

---

layouts/playlist/index.tsx
layouts/playlist/utils.ts
pages/playlist/[playlist].tsx
utils/spotifyCalls/getPlaylistDetails.ts

fix save to playlist redirects before adding tracks

---

.github/workflows/publish-coverage.yml
.github/workflows/tests.yml
package-lock.json
package.json
scripts/open-coverage-report.sh

add coverage report

---

components/UserWidget.tsx
middleware.ts
pages/dashboard.tsx
pages/preferences.tsx
utils/getTranslations.ts

Part of https://github.com/MarcoMadera/Rindu/issues/136

add settings page

---

components/CardContentContextMenu.tsx
components/CardTrack.tsx
components/CardTrackContextMenu.tsx
components/DeviceConnectControl.tsx
components/EditPlaylistDetails.tsx
components/EmbedModal.tsx
components/EpisodeCard.tsx
components/FullScreenLyrics.tsx
components/NowPlaying.tsx
components/Player.tsx
components/PlaylistText.tsx
components/ProgressBar.tsx
components/RemoveTracksModal.tsx
components/SideBar.tsx
components/SpotifyPlayer.tsx
components/__tests__/CardContent.spec.tsx
components/__tests__/CardTrack.spec.tsx
hooks/useSpotifyPlayer.ts
layouts/FullScreenPlayer.tsx
layouts/playlist/index.tsx
pages/album/[albumId].tsx
pages/api/radio-cover.tsx
pages/show/[show].tsx
pages/track/[id].tsx
types/toast.ts
utils/capitalizeFirstLetter.ts
utils/getTranslations.ts
utils/templateReplace.ts

add some translations

---

components/icons/Heart.tsx
pages/track/[id].tsx

fix like button reset to its default state if it is not liked

---

.vscode/extensions.json

Add workspace recommended extensions

---

components/CardTrack/PlayButtonIcon.tsx

Fix prop name

---

components/FullScreenLyrics/FullScreenLyrics.tsx
utils/getLinesFittingCanvas.ts

pip lyrics calculations

---

components/FullScreenLyrics/FullScreenLyrics.tsx
components/FullScreenQueue/FullScreenQueue.tsx
components/ProgressBar/ProgressBar.tsx
components/SpotifyPlayer/SpotifyPlayer.tsx
components/TopBar/TopBar.tsx
layouts/AppContainer.tsx
layouts/FullScreenPlayer.tsx

fix progress bar in full screen

---

components/PlaybackExtraControls/PlaybackExtraControls.tsx

fix pip button showing in firefox

---

components/ProgressBar/ProgressBar.tsx
components/SearchResults/SearchResults.tsx
components/SearchResults/index.ts
components/index.ts
pages/search.tsx
utils/playCurrentTrack.ts

fix: Playing now is not updating with the correct info for open users

---

components/CardTrackContextMenu/CardTrackContextMenu.tsx
components/ProgressBar/ProgressBar.tsx
hooks/useSpotifyPlayer.ts
pages/dashboard.tsx

progress bar fix

---

components/CardSubTitle/CardSubTitle.tsx
components/CardTrackContextMenu/CardTrackContextMenu.tsx
components/Carousel/Carousel.tsx
components/ContextMenu/ContextMenu.tsx
components/EpisodeCard/EpisodeCard.stories.tsx
components/EpisodeCard/EpisodeCard.tsx
components/FullScreenQueue/FullScreenQueue.tsx
components/PageHeader/PageHeader.tsx
components/ShortCuts/ShortCuts.tsx
components/TopBar/TopBar.tsx
components/icons/Playing.tsx
hooks/useDisableGlobalContextMenu.ts
layouts/playlist/index.tsx
pages/show/[show].tsx
types/spotify.ts
utils/contextMenu.ts

fixes fixes fixes

---

components/ContentContainer/ContentContainer.tsx
components/NowPlaying/NowPlaying.tsx
components/PageHeader/PageHeader.tsx
components/SpotifyPlayer/SpotifyPlayer.tsx
components/Toast/Toast.tsx
components/ToastCard/ToastCard.tsx
hooks/useDynamicFontSize.ts
layouts/FullScreenPlayer.tsx
layouts/playlist/index.tsx
utils/getMainColorFromImage.ts

fix mobile styles

---

components/SearchInput/SearchInput.tsx
components/SearchInput/index.ts
components/Searchable/Searchable.tsx
components/Searchable/index.ts
components/TextHighlighter/TextHighlighter.tsx
components/TextHighlighter/index.ts
components/icons/Delete.tsx
components/icons/index.tsx
components/index.ts
pages/preferences.tsx
utils/extractTextFromChildren.ts
utils/index.ts

add searchable filtered and highlighted area

---

components/CommandLine/CommandLine.tsx
utils/getMonth.ts

https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#:~:text=Android-,%22Unidentified%22,-The%20user%20agent

unidentified

---

components/FullScreenLyrics/FullScreenLyrics.tsx
components/PlaybackExtraControls/PlaybackExtraControls.tsx

hide pip button to non premium users

---

package-lock.json
package.json

This PR has been opened to upgrade next from version 14.2.10 to 14.2.11.
- Updated next from version 14.2.10 to 14.2.11.
> [!IMPORTANT]
>
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name","snyk_project_url","snyk_p …

upgrade: [next]

---

package-lock.json
package.json

This PR has been opened to upgrade dompurify from version 3.1.6 to 3.1.7.
- Updated dompurify from version 3.1.6 to 3.1.7.
- Files changed: 
More details can be found in the Snyk project [MarcoMadera&#x2F;Rindu:package.json](https:&#x2F;&#x2F;app.snyk.io&#x2F;org&#x2F;marcomadera&#x2F;project&#x2F;5e63f201-969f-40ea-be51-e8d078fa6dbe).
> [!IMPORTANT]
>
[//]: # (snyk:metadata:{"prId":"9e5dc285-9c19-4904-ad5c-ded763026192","prPublicId":"9e5dc285-9c19-4904-ad5c-ded763026192","packageManager":"npm","projectPublicId":"5e63f201-969f-40ea-be51-e8d078fa6dbe","projectUrl":"https://app.snyk.io/org/marcomadera/project/5e63f201- …

upgrade: [dompurify]

---

.github/workflows/tests.yml

- **update actions**
- **update tests action**

update tests action

---

.github/workflows/pull-submodule-update.yml

- **updates**
- **use update workflow**

use work update flow

---

components/TrackListHeader/TrackListHeader.tsx

rootMargin can be --{height}px if height is small

fix runtime error

---

components/CardContainer/CardContainer.tsx
components/NowPlaying/NowPlaying.tsx

fix #270 marquee

---

package-lock.json
package.json

This PR has been opened to upgrade @vercel&#x2F;analytics from version 1.4.0 to 1.4.1.
- Updated @vercel&#x2F;analytics from version 1.4.0 to 1.4.1.
> [!IMPORTANT]
>
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name …

upgrade: [@vercel&#x2F;analytics]

---

package-lock.json
package.json

This PR addresses known vulnerabilities in next.
- Updated next from version 15.0.3 to 15.1.2.
More details can be found in the Snyk project [MarcoMadera&#x2F;Rindu:package.json](https:&#x2F;&#x2F;app.snyk.io&#x2F;org&#x2F;marcomadera&#x2F;project&#x2F;5e63f201-969f-40ea-be51-e8d078fa6dbe?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr).
> [!IMPORTANT]
>
fix applied by marcomadera
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name","snyk_project_url","snyk_pull_request_type","snyk_org_name"],"fieldsUsed":["commitMessage","description","title"]},"d …

fix: [next]

---

utils/spotifyCalls/repeat.ts

fix #412 repeat toggle not working

---

hooks/useMediaSession.ts

fix duration

---

components/VirtualizedList/TracksList.tsx
components/VirtualizedList/VirtualizedList.tsx

I like the way you bite,
Keep me up all night

load everything

---

package-lock.json
package.json

This PR addresses known vulnerabilities in dompurify.
- Updated dompurify from version 3.2.3 to 3.2.4.
More details can be found in the Snyk project [MarcoMadera&#x2F;Rindu:package.json](https:&#x2F;&#x2F;app.snyk.io&#x2F;org&#x2F;marcomadera&#x2F;project&#x2F;5e63f201-969f-40ea-be51-e8d078fa6dbe?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr).
> [!IMPORTANT]
>
fix applied by marcomadera
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name","snyk_project_url","snyk_pull_request_type","snyk_org_name"],"fieldsUsed":["commitMessage","description","tit …

fix: [dompurify]

---

components/CardTrack/TrackDetails.tsx
components/NowPlaying/NowPlaying.tsx
components/Placeholder/Placeholder.tsx
layouts/FullScreenPlayer.tsx
pages/track/[id].tsx

vi gente correr

---

components/DPIPLyrics/DPIPLyrics.tsx
components/DPIPLyrics/index.ts
components/FullScreenLyrics/FullScreenLyrics.tsx
components/FullScreenLyrics/LyricLine.tsx
components/LyricsPIPButton/LyricsPIPButton.tsx
components/PortalTarget/PortalTarget.ts
components/index.ts
context/LyricsContextProvider.tsx
context/SpotifyContext.tsx
hooks/useLyrics.ts
hooks/useLyricsInPictureInPicture.ts
types/spotify.ts
utils/errors.ts
utils/fullScreen.ts

new pip window

---

components/PlayerControls/PlayerControls.tsx
components/ProgressBar/ProgressBar.tsx
components/Slider/Slider.tsx
hooks/useSpotifyPlayer.ts
layouts/FullScreenPlayer.tsx

fix slider #263

---

components/FullScreenLyrics/FullScreenLyrics.tsx
components/SpotifyPlayer/SpotifyPlayer.tsx
components/TopBar/TopBar.tsx
hooks/useHeader.ts
hooks/useLyricsInPictureInPicture.ts
hooks/usePictureInPicture.ts
layouts/AppContainer.tsx

fixes of fixes

---

utils/cookies.ts

fix login secure issue

---

components/FullScreenLyrics/FullScreenLyrics.tsx
components/FullScreenLyrics/LyricLine.tsx
components/ProgressBar/ProgressBar.tsx
context/LyricsContextProvider.tsx
context/SpotifyContext.tsx
types/spotify.ts

This should have been in the lyrics context or not be added at all.
_Originally posted by @MarcoMadera in https://github.com/MarcoMadera/Rindu/pull/396#discussion_r1859191699_

solve comment

---

.env.example
utils/getArtistsOfTheWeek.ts
utils/getTracksOfTheWeek.ts

handle dashboard error

---

components/CountDown/CountDown.tsx
components/CountDown/index.ts
components/FullScreenLyrics/FullScreenLyrics.tsx
components/FullScreenLyrics/LyricLine.tsx
components/index.ts

add countdown

---

components/CountDown/CountDown.tsx
components/FullScreenLyrics/FullScreenLyrics.tsx

sometimes it is just hard to know the exact time so I added

add number

---

components/DPIPLyrics/DPIPLyrics.tsx
components/FullScreenLyrics/FullScreenLyrics.tsx
components/FullScreenLyrics/LyricLine.tsx
components/LyricsPIPButton/LyricsPIPButton.tsx
components/MiniPlayer/MiniPlayer.tsx
components/MiniPlayer/index.ts
components/Player/Player.tsx
components/ProgressBar/ProgressBar.tsx
components/ScrollableText/ScrollableText.tsx
components/Slider/Slider.tsx
components/index.ts
context/AppContextProvider.tsx
context/LyricsContextProvider.tsx

consolidate mini player

---

components/MiniPlayer/MiniPlayer.tsx
utils/__tests__/getMainColorFromImage.spec.ts
utils/getMainColorFromImage.ts

- **change color algo**
- **color to test**

color to music

---

components/FullScreenLyrics/FullScreenLyrics.tsx
components/MiniPlayer/MiniPlayer.tsx
components/Slider/Slider.tsx

fix image and slider dot

---

package-lock.json
package.json

This PR has been opened to upgrade html-entities from version 2.5.2 to 2.5.3.
- Updated html-entities from version 2.5.2 to 2.5.3.
> [!IMPORTANT]
>
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name","snyk_project_ur …

upgrade: [html-entities]

---

package-lock.json
package.json

This PR has been opened to upgrade isomorphic-dompurify from version 2.22.0 to 2.24.0.
- Updated isomorphic-dompurify from version 2.22.0 to 2.24.0.
> [!IMPORTANT]
>
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name …

upgrade: [isomorphic-dompurify]

---

package-lock.json
package.json

This PR has been opened to upgrade cheerio from version 1.0.0 to 1.1.0.
- Updated cheerio from version 1.0.0 to 1.1.0.
> [!IMPORTANT]
>
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name","snyk_project_url","snyk_pul …

upgrade: [cheerio]

---

package-lock.json
package.json

This PR has been opened to upgrade simplebar-react from version 3.3.0 to 3.3.1.
- Updated simplebar-react from version 3.3.0 to 3.3.1.
> [!IMPORTANT]
>
[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":["package_name","package_from","package_to","files_changed","snyk_project_name","snyk_projec …

upgrade: [simplebar-react]
